version: "3.9"
services:
  branch_checker:
    build: 
      context: ./python
      dockerfile: ../docker/Dockerfile
    env_file: ./env_vars.txt
    volumes:
      - cache_volume:/data
    restart: on-failure
volumes:
  cache_volume: {}
