apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "feature-stand.fullname" . }}
  labels:
    {{- include "feature-stand.labels" . | nindent 4 }}
data:
  index.html: {{ .Values.configmap.index | nindent 4 }} 